cabal-version:   3.0
name:            eris
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

flag dev
  description: Be less pedantic for rapid rebuilds
  default: False
  manual: True

common shared-config
    default-language: GHC2024
    if !flag(dev)
      ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror
    default-extensions:
        OverloadedStrings
        TemplateHaskell
        TypeFamilies
    build-depends:
        base >= 4.14 && < 5,
        relude,
        text,
        lens,
        QuickCheck
    mixins:
        base hiding (Prelude)

library
    import:           shared-config
    hs-source-dirs:   src
    build-depends:    array
                    , mtl
                    , containers
                    , discord-haskell
                    , scientific
                    , directory
    exposed-modules: Prelude,
                     Eris.Commands.Core,
                     Eris.Commands.Registration,
                     Eris.Commands.Arguments,
                     Eris.Commands,
                     Eris.Token,
                     Eris.Handler,
                     Eris
