cabal-version:   3.0
name:            weed-lang
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

common warnings
    ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror

library
    import:           warnings
    hs-source-dirs:   src
    default-language: Haskell2010
    build-tool-depends: alex:alex >= 3.2
                      , happy:happy >= 1.20
    build-depends:    base
                    , array
                    , mtl
                    , containers
                    , QuickCheck
    exposed-modules:  AST
                    , PrettyPrint
                    , TypeChecker
                    , TypeChecker.Types
                    , TypeChecker.Subst
                    , TypeChecker.BuiltinTypes
                    , TypeChecker.Infer
                    , Evaluator
                    , Evaluator.Types
                    , Evaluator.Builtins
                    , Evaluator.WeedNumber

executable weed
    import:           warnings
    main-is:          Main.hs
    hs-source-dirs:   app
    default-language: Haskell2010
    build-depends:    base
                    , weed-lang

test-suite test-weed
    type:             exitcode-stdio-1.0
    main-is:          Tests.hs
    hs-source-dirs:   test
    default-language: Haskell2010
    build-depends:    base
                    , weed-lang
                    , tasty
                    , tasty-hunit
                    , containers
    other-modules:    Tests.TypeChecker
                    , Tests.Evaluator
