cabal-version:   3.0
name:            weed-lang
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

flag dev
  description: Disable warnings-as-errors for faster development
  default: False
  manual: True

common shared-config
    default-language: GHC2024
    if !flag(dev)
      ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror
    default-extensions:
        OverloadedStrings
        TemplateHaskell
    build-depends:
        base >= 4.14 && < 5,
        relude,
        text,
        lens
    mixins:
        base hiding (Prelude),

library
    import:           shared-config
    hs-source-dirs:   src
    build-tool-depends: alex:alex >= 3.2
                      , happy:happy >= 1.20
    build-depends:    array
                    , mtl
                    , containers
                    , QuickCheck
    exposed-modules:  Prelude
                    , AST
                    , Parser.Lexer
                    , Parser.SurfaceParser
                    , Parser.Lowerer
                    , TypeChecker
                    , TypeChecker.Types
                    , TypeChecker.Subst
                    , TypeChecker.BuiltinTypes
                    , TypeChecker.Infer
                    , Evaluator
                    , Evaluator.Types
                    , Evaluator.Assertions
                    , Evaluator.Builtins
                    , Evaluator.DicePrimitives
                    , Evaluator.WeedNumber
                    , Evaluator.Metadata
                    , Formatting.ANSI
                    , Formatting.Metadata
                    , Formatting.Pretty
                    , TowerNumber.Core
                    , TowerNumber.Utils
                    , TowerNumber.Parse

executable weed
    import:           shared-config
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    weed-lang
                    , haskeline

test-suite test-weed
    import:           shared-config
    type:             exitcode-stdio-1.0
    main-is:          Tests.hs
    hs-source-dirs:   test
    build-depends:    weed-lang
                    , tasty
                    , tasty-hunit
                    , containers
    other-modules:    Tests.Lexer
                    , Tests.SurfaceParser
                    , Tests.Lowerer
                    , Tests.TypeChecker
                    , Tests.Evaluator
                    , Tests.TowerNumber
