cabal-version:   3.0
name:            weed-shds
version:         0.1.0.0
license:         MIT
author:          Bazinga_9000
maintainer:      bazninethousand@gmail.com
build-type:      Simple

flag dev
  description: Be less pedantic for rapid rebuilds
  default: False
  manual: True

common shared-config
    default-language: GHC2024
    if !flag(dev)
      ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wpartial-fields -Wredundant-constraints -Wmissing-home-modules -Widentities -Werror
    default-extensions:
        OverloadedStrings
        TemplateHaskell
        TypeFamilies
    build-depends:
        base >= 4.14 && < 5,
        relude,
        text,
        lens,
        QuickCheck
    mixins:
        base hiding (Prelude)

executable weed
    import:           shared-config
    main-is:          Main.hs
    hs-source-dirs:   app
    build-depends:    weed-lang
                    , directory
                    , discord-haskell
    other-modules:    Commands,
                      Commands.Core,
                      Commands.Ping,
                      Commands.Roll,
                      Formatting
