module TypeChecker where

import AST
import Control.Monad.Except
import Control.Monad.RWS
import TypeChecker.BuiltinTypes
import TypeChecker.Infer
import TypeChecker.Subst
import TypeChecker.Types

-- infer the type of an untyped expression,
-- emitting all necesssary constraints for the solver to un
infer :: CoreUntypedExpr -> Infer (WeedType, CoreTypedExpr)
infer (CUNumber n) = return $ (TNumber, CTNumber n)
infer (CUBool b) = return $ (TBool, CTBool b)
infer (CUUnit) = return $ (TUnit, CTUnit)
infer (CUList []) = do
  t <- fresh
  return $ (mkList t, CTList t [])
infer (CUList (x : xs)) = do
  t <- fresh
  (tx, cx) <- infer x
  (txs, cxs) <- infer (CUList xs)
  unify t tx
  unify (mkList t) txs
  let listType = mkList t
  newList <- (CTList listType) <$> appendCList cx cxs
  return $ (listType, newList)
  where
    appendCList :: CoreTypedExpr -> CoreTypedExpr -> Infer [CoreTypedExpr]
    appendCList cx (CTList _ cxs) = return $ (cx : cxs)
    appendCList _ e = throwError $ "TC Bug: Expected a list, got " ++ show e
infer (CUIdentifier (B builtin)) = do
  t <- builtinType builtin >>= instantiate
  return $ (t, CTIdentifier t (B builtin))
infer (CUIdentifier ident) = (\t -> (t, CTIdentifier t ident)) <$> lookupEnv ident
infer (CULambda ident body) = do
  tv <- fresh
  (tb, cb) <- inEnv (ident, ForAll [] [] tv) (infer body)
  let tl = TFunction tv tb
  return (tl, CTLambda tl ident cb)
infer (CUApply f arg) = do
  (tf, cf) <- infer f
  (ta, ca) <- infer arg

  tr <- fresh

  -- Grab the current state so we can see the true structural shapes
  s <- currentSubst <$> get
  let tf' = apply s tf
  let ta' = apply s ta

  -- Attempt eager structural unification
  case unify' tf' (TFunction ta' tr) of
    -- SUCCESS: Standard application
    Right newSub -> do
      modify (\curr -> curr {currentSubst = newSub `compose` s})
      return (tr, CTApply tr cf ca)

    -- FAILURE: Intercept the structural mismatch to attempt coercion
    Left origErr -> case tf' of
      TFunction texp tret ->
        case (texp, ta') of
          -- RULE 2: Pool Collapse (Expected: Dice Number, Actual: Pool Number)
          (TApp TDice TNumber, TApp TPool TNumber) -> do
            unify tret tr
            let tcollapse = TFunction (TApp TPool TNumber) (TApp TDice TNumber)
            let collapse = CTIdentifier tcollapse (B Collapse)
            let coerced = CTApply (TApp TDice TNumber) collapse ca
            return (tret, CTApply tret cf coerced)

          -- RULE 3: Pool Mapping (Expected: [a], Actual: Pool a)
          (TApp TList texpInner, TApp TPool tInner) -> do
            unify texpInner tInner
            let mapped = TApp TDice tret
            unify tr mapped
            return (mapped, CTMapPool mapped cf ca)

          -- RULE 1: Scalar Lifting (Expected: Dice a, Actual: a (but NOT a Dice/Pool))
          (TApp TDice texpInner, tscalar)
            | not (isDiceOrPool tscalar) -> do
                unify texpInner tscalar
                unify tret tr
                let tconst = TFunction tscalar tret
                let constNode = CTIdentifier tconst (B Constant)
                let coercedArg = CTApply texp constNode ca
                return (tr, CTApply tr cf coercedArg)
          _ -> throwError origErr
      _ -> throwError origErr
infer (CUIf cond t f) = do
  (tc, cc) <- infer cond
  (tt, ct) <- infer t
  (tf, cf) <- infer f
  unify tc TBool
  unify tt tf
  return (tt, CTIf tc cc ct cf)
infer (CULet ident val body) = do
  -- infer the value and trap its class constraints
  ((tVal, typedVal), valConstraints) <- listen $ censor (const []) (infer val)

  -- generalize the value's type scheme
  scheme <- generalize tVal valConstraints

  -- extend the environment and infer the body
  (tBody, typedBody) <- inEnv (ident, scheme) (infer body)
  return (tBody, CTLet tBody ident typedVal typedBody)

-- solve the constraints generated by infer
solve :: Subst -> [TypeConstraint] -> Either TypeError ()
solve finalSubst constraints =
  mapM_ solveOne $ apply finalSubst constraints
  where
    baseType :: WeedType -> WeedType
    baseType (TApp t _) = baseType t
    baseType t = t

    solveOne :: TypeConstraint -> Either TypeError ()
    solveOne (CInstanceOf cls t) =
      let base = baseType t
       in case (cls, base) of
            -- Functor
            (CFunctor, TList) -> Right ()
            (CFunctor, TDice) -> Right ()
            (CFunctor, TPool) -> Right ()
            -- Monad
            (CMonad, TList) -> Right ()
            (CMonad, TDice) -> Right ()
            (CMonad, TPool) -> Right ()
            -- Rollable
            (CRollable, TDice) -> Right ()
            (CRollable, TPool) -> Right ()
            -- Ambiguous top-level type variable
            (c, TVar tv) -> Left $ "Ambiguous type variable " ++ show tv ++ " for class " ++ show c
            -- Missing instance
            (c, t') -> Left $ "No instance for " ++ show c ++ " for type " ++ show t'

typeCheck :: CoreUntypedExpr -> Either TypeError CoreTypedExpr
typeCheck expr = do
  -- infer, fetch all constraints
  ((_, typed), finalState, constraints) <- runExcept $ runRWST (infer expr) emptyEnv freshState
  let subst = currentSubst finalState
  -- solve the constraints
  solve subst constraints
  -- if we got here, constraint solving succeded, apply the final subs to concretize every node's type
  return $ apply subst typed
