name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    uses: Bazinga9000/chashmal/.github/workflows/nix-ci.yaml@main
